2.6.32: Fix incorrect case fall-through
GCC warns about several missing fall-through comments. This commit fixes
those warnings and also addresses a real issue in the 2.6.32 tree that
results in many of the Cintiq devices being improperly initialized. The
fall-through causes these devices to be initialized as Intuos devices
rather than the Cintiqs.

wacom_wac.c: In function ‘wacom_setup_input_capabilities’:
wacom_wac.c:2300:3: error: this statement may fall through
  [-Werror=implicit-fallthrough=]
   input_set_abs_params(input_dev, ABS_Z, -900, 899, 0, 0);
   ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
wacom_wac.c:2302:2: note: here
  case INTUOS3:
  ^~~~

Signed-off-by: Jason Gerecke <jason.gerecke@wacom.com>