github: Do not fail with error when modpost can't find symbols
When running the main Github action with more recent kernels, the build
fails with a series of errors similar to the following:

~~~
WARNING: Module.symvers is missing.
         Modules may not have dependencies or modversions.
         You may get many unresolved symbol errors.
         You can set KBUILD_MODPOST_WARN=1 to turn errors into warning
         if you want to proceed at your own risk.
ERROR: modpost: "sprintf" [/home/runner/work/input-wacom/input-wacom/4.5/wacom.ko] undefined!
ERROR: modpost: "strscpy" [/home/runner/work/input-wacom/input-wacom/4.5/wacom.ko] undefined!
ERROR: modpost: "devm_led_trigger_register" [/home/runner/work/input-wacom/input-wacom/4.5/wacom.ko] undefined!
[...]
~~~

These errors seem to be a result of us building against a source tree
that was never itself built. Symbols like 'sprintf' which the kernel
binary would provide are not available, causing these messages. This
commit takes the advice given in the message, using a makefile flag to
transform these into non-fatal warnings.

Signed-off-by: Jason Gerecke <jason.gerecke@wacom.com>